-- AlterTable
ALTER TABLE "TopCategory" ADD COLUMN "icon" TEXT,
ADD COLUMN "sortOrder" INTEGER NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE "Category" ADD COLUMN "icon" TEXT,
ADD COLUMN "sortOrder" INTEGER NOT NULL DEFAULT 0;
